name: Fetch Releases

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  fetch-assets:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
      - name: Use Node.js 18.12.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.12.1
      - name: Install dependencies
        run: npm install
      - name: Fetch RSS Feeds
        run: npm run fetch-assets
      - name: commit file
        working-directory: src
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m 'update rss.json'
          git push origin main
