name: Fetch Releases

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  create-releases-report-job:
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: pip setting
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: run python
        working-directory: scripts
        run: |
          python releases.py
          mv *.json ./../src/data/releases/
      - name: commit file
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m 'update release data'
          git push origin main
